tags:
  # tags.pgo enables the installation of CrunchyData PGO
  pgo: true
  # tags.postgrescluster enables the installation of a PGO Postgres cluster
  postgrescluster: true

# pgo optional dependency options (see: https://access.crunchydata.com/documentation/postgres-operator/latest/installation/helm)
pgo:
  # pgo.singleNamespace is set to true to only watch the installation namespace
  singleNamespace: true
  # pgo.debug is set to false to disable pgo debug logging
  debug: false
# postgrescluster optional dependency options (see: https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/create-cluster#use-helm-to-create-a-postgres-cluster)
postgrescluster:
  postgresVersion: 16
