# name is the name of our mastodon instance
# name: "mastodon"

# tags enables or disables certain features
tags:
  # tags.pgo enables the installation of CrunchyData PGO
  pgo: true
  # tags.postgrescluster enables the installation of a PGO Postgres cluster
  postgrescluster: true

# pgo optional dependency options (see: https://access.crunchydata.com/documentation/postgres-operator/latest/installation/helm)
pgo:
  # pgo.singleNamespace is set to true to only watch the installation namespace
  singleNamespace: true
  # pgo.debug is set to false to disable pgo debug logging
  debug: false

# postgrescluster optional dependency options (see: https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/create-cluster#use-helm-to-create-a-postgres-cluster)
postgrescluster:
  # postgrescluster.databaseInitSQL points to a configuration file that bootstraps the database by creating a user schema for the mastodon database (see: https://www.crunchydata.com/blog/be-ready-public-schema-changes-in-postgres-15)
  databaseInitSQL:
    name: "postgrescluster-bootstrap-config"
    key: "bootstrap.sql"
  users:
  - name: mastodon
    databases:
    - mastodon
