---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mastodon-standalone.env.configMapName" . | quote }}
  labels:
    {{- include "mastodon-standalone.labels" . | nindent 4 }}
data:
  LOCAL_DOMAIN: {{ required "Please set the domain for federation (key: localDomain)" .Values.localDomain | quote }}
  SINGLE_USER_MODE: {{ default false .Values.singleUserMode }}
  REDIS_HOST: {{ required "Please provide the Redis instance hostname" .Values.redis.host | quote }}
  REDIS_PORT: {{ default 6379 .Values.redis.port }}
  DB_HOST: {{ required "Please provide the database hostname" .Values.postgres.host | quote }}
  DB_PORT: {{ default 5432 .Values.postgres.port }}
  DB_USER: {{ default "mastodon" .Values.postgres.user | quote }}
  DB_NAME: {{ required "Please provide the Postgres database name" .Values.postgres.name | quote }}
  {{- if .Values.smtp.enabled }}
  SMTP_SERVER: {{ required "Please provide a SMTP host" .Values.smtp.host | quote }}
  SMTP_PORT: {{ default 587 .Values.smtp.port }}
  SMTP_FROM_ADDRESS: {{ default (printf "notification@%s" .Values.localDomain) .Values.smtp.fromAddress | quote }}
  SMTP_LOGIN: {{ required "Please provide a SMTP login" .Values.smtp.user | quote }}
  {{- end }}
