{{- define "mastodon-standalone.web.labels" -}}
app.kubernetes.io/component: web
app.kubernetes.io/part-of: rails
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-web" (include "mastodon-standalone.fullname" .) | quote }}
  labels:
    {{- include "mastodon-standalone.labels" . | nindent 4 }}
    {{- include "mastodon-standalone.web.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "mastodon-standalone.selectorLabels" . | nindent 6 }}
      {{- include "mastodon-standalone.web.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        {{- include "mastodon-standalone.rollingPodAnnotations" . | nindent 8 }}
      labels:
        {{- include "mastodon-standalone.labels" . | nindent 8 }}
        {{- include "mastodon-standalone.web.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mastodon-standalone.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ printf "%s-web" .Chart.Name | quote }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ include "mastodon-standalone.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - bundle
        - exec
        - puma
        - -C
        - config/puma.rb
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
            - name: "Host"
              value: {{ printf "%s:3000" .Values.localDomain | quote }}
        readinessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
            - name: "Host"
              value: {{ printf "%s:3000" .Values.localDomain | quote }}
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          failureThreshold: 30
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        {{- include "mastodon-standalone.dataVolumeMounts" . | nindent 8 }}
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "mastodon-standalone.env.containersSnippet" . | nindent 8 }}
      volumes:
      {{- include "mastodon-standalone.dataVolumes" . | nindent 6 }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
