{{/*
Deploy the HTTP routes only if networking is enabled and on gateway api type.
*/}}
{{- if and (.Values.networking.enabled) (eq .Values.networking.type "gateway") }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mastodon-standalone.fullname" . | quote }}
  labels:
    {{- include "mastodon-standalone.labels" . | nindent 4 }}
spec:
  hostnames:
  - {{ .Values.localDomain | quote }}
  parentRefs:
  {{- toYaml .Values.networking.gateway.parentRefs | nindent 2 }}
  rules:
  - matches:
    - path:
        type: "PathPrefix"
        value: "/"
    backendRefs:
    - name: {{ printf "%s-web" (include "mastodon-standalone.fullname" .) | quote }}
      port: {{ .Values.services.web.port }}
  - matches:
    - path:
        type: "PathPrefix"
        value: "/api/v1/streaming"
    backendRefs:
    - name: {{ printf "%s-streaming" (include "mastodon-standalone.fullname" .) | quote }}
      port: {{ .Values.services.streaming.port }}
{{- end }}
