{{- if not .Values.persistence.existingClaims.system -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mastodon-standalone.persistence.system.pvcName" . | quote }}
  labels:
    {{- include "mastodon-standalone.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  {{- with .Values.persistence.resources.system }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end}}
{{- end }}
