---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "secret-rw"
  labels: {{ include "mastodon-standalone.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [{{ include "mastodon-standalone.secretName" . | quote }}]
  verbs: ["get", "update", "patch"]
