---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "serviceaccount"
  labels: {{ include "mastodon-standalone.labels" . | nindent 4 }}
subjects:
- kind: "ServiceAccount"
  name: {{ include "mastodon-standalone.serviceAccountName" . | quote }}
roleRef:
  kind: "Role"
  name: "secret-rw"
