{{/*
Install this Secret only if it doesn't already exist or if existingSecret is not set. The Vapid keys pair is created by job-generate-vapid-key.
*/}}
{{- if not (or (.Values.existingSecret) (lookup "v1" "Secret" .Release.Namespace "mastodon-standalone.secretName")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon-standalone.env.secretName" . | quote }}
  labels: {{ include "mastodon-standalone.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  SECRET_KEY_BASE: {{ include "mastodon-standalone.randHex" 64 | b64enc | quote }}
  OTP_SECRET: {{ include "mastodon-standalone.randHex" 64 | b64enc | quote }}
{{- end }}
