---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-web" (include "mastodon-standalone.fullname" .) | quote }}
  labels:
spec:
  type: {{ .Values.services.web.type }}
  ports:
    - port: {{ .Values.services.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mastodon-standalone.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
