---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-streaming" (include "mastodon-standalone.fullname" .) | quote }}
  labels:
spec:
  type: {{ .Values.services.streaming.type }}
  ports:
    - port: {{ .Values.services.streaming.port }}
      targetPort: streaming
      protocol: TCP
      name: streaming
  selector:
    {{- include "mastodon-standalone.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
